### ISSUE TITLE
Figure out why the image is blurry

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#124]
![Screen Shot 2021-03-21 at 10 39 04 AM](https://user-images.githubusercontent.com/411114/111901015-e1230300-8a35-11eb-8448-d2172d63ddbd.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Hey @davidgatti 

Are you able to provide these images as svg?

The source is currently jpg and they are being reduced by about 2/3 of their original size at an odd ratio so that is likely to result in some blurring.  If you don't have the original svg, I'd suggest we re-size these manually rather than letting the browser try to do it.

**Comment by davidgatti** [comment]
This are hand drown images so there is no VGS. In this case could you resize them to the right size, but also add an option for @2 so we display a higher res on retina displays? Ideally this would be nice if it was done at build time, so I replace an image, and all the right version get created?

**Comment by x5hwuk7nc6jsudcc** [comment]
Hi @davidgatti please check out PR https://github.com/0x4447-office/0x4447_template_office_jekyll/pull/134 which looks like it resolves the issue for me.

From testing this, it looks to me like the issue is around the source image aspect ratio being 660:989 and when this was reduced the desired 220px wide the ratio became 220:329.66666666667.  This seemed to create some blur in some browsers.

In addition to fixing the above, I also re-saved these as png, which is a better format for these types of images. I've also compressed them.

Let me know how the above goes and if it resolves the issue.

In relation to the comments above around re-sizing these correctly, and have srcset for 2x etc., this can all be done (e.g. using Imagemin on build) but it will require some significant changes to the liquid templates.  This isn't necessary to solve this specific issue, but if you want to create a new GitHub issue, I'm happy to quote it and look at it as a separate item.
