### ISSUE TITLE
Two things for the table

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#96]
- order by low to high
- display the 1000 separator

![Screen Shot 2020-12-04 at 9 42 05 AM](https://user-images.githubusercontent.com/411114/101143798-b09a9300-3617-11eb-98fe-9c05bb834dcd.png)

**Comment by edhenderson** [comment]
I've been looking into this. In short, this is not possible using Liquid and YAML.

Possible solutions:
1. change YAML data to be an object rather than an array of arrays (this allows you to sort on the last column)
2. Use Javascript to target the numbers after they render and format them (this way you can leave data alone)
3. Sort the data manually
4. Format the data manually

Let me know what solution you would like.

**Comment by davidgatti** [comment]
Option 2 sounds good.

**Comment by edhenderson** [comment]
Option 2 it is, thanks for clarifying. I will make this change ASAP.
